### ISSUE TITLE
Exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `POST

### ISSUE THREAD

**Issue by Mirocow** [zelenin/telegram-bot-api#11]
```
Exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `POST https://api.telegram.org/uuuuuu:iiiiiiiiiiiiii/getUpdates` resulted in a `502 Bad Gateway` response:
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
 (truncated...)
'

in /home/101112.pw/httpdocs/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107

Stack trace:
#0 /home/101112.pw/httpdocs/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/101112.pw/httpdocs/vendor/guzzlehttp/promises/src/Promise.php(201): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/101112.pw/httpdocs/vendor/guzzlehttp/promises/src/Promise.php(154): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/101112.pw/httpdocs/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/101112.pw/httpdocs/vendor/guzzlehttp/promises/src/Promise.php(242): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /home/101112.pw/httpdocs/vendor/guzzlehttp/promises/src/Promise.php(219): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/101112.pw/httpdocs/vendor/guzzlehttp/promises/src/Promise.php(262): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/101112.pw/httpdocs/vendor/guzzlehttp/promises/src/Promise.php(221): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /home/101112.pw/httpdocs/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/101112.pw/httpdocs/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Promise\Promise->wait()
#10 /home/101112.pw/httpdocs/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('post', 'https://api.tel...', Array)
#11 /home/101112.pw/httpdocs/vendor/zelenin/telegram-bot-api/Client.php(50): GuzzleHttp\Client->__call('post', Array)
#12 /home/101112.pw/httpdocs/vendor/zelenin/telegram-bot-api/Client.php(50): GuzzleHttp\Client->post('https://api.tel...', Array)
#13 /home/101112.pw/httpdocs/vendor/zelenin/telegram-bot-api/Api.php(44): Zelenin\Telegram\Bot\Client->request('getUpdates', Array)
#14 /home/101112.pw/httpdocs/vendor/zelenin/telegram-bot-api/Api.php(259): Zelenin\Telegram\Bot\Api->request('getUpdates', Array)
#15 /home/101112.pw/httpdocs/vendor/zelenin/telegram-bot-api/Daemon/Daemon.php(68): Zelenin\Telegram\Bot\Api->getUpdates(Array)
#16 /home/101112.pw/httpdocs/vendor/zelenin/telegram-bot-api/Daemon/Daemon.php(55): Zelenin\Telegram\Bot\Daemon\Daemon::getUpdates()
#17 [internal function]: Zelenin\Telegram\Bot\Daemon\Daemon->Zelenin\Telegram\Bot\Daemon\{closure}('0000000034ef15d...', NULL)
#18 /home/101112.pw/httpdocs/vendor/amphp/amp/lib/NativeReactor.php(288): call_user_func(Object(Closure), '0000000034ef15d...', NULL)
#19 /home/101112.pw/httpdocs/vendor/amphp/amp/lib/NativeReactor.php(221): Amp\NativeReactor->executeTimers()
#20 /home/101112.pw/httpdocs/vendor/amphp/amp/lib/NativeReactor.php(70): Amp\NativeReactor->doTick(false)
#21 /home/101112.pw/httpdocs/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(Object(Closure))
#22 /home/101112.pw/httpdocs/vendor/zelenin/telegram-bot-api/Daemon/Daemon.php(60): Amp\run(Object(Closure))
#23 /home/101112.pw/httpdocs/vendor/mirocow/yii2-telegram-api/src/controllers/BotController.php(87): Zelenin\Telegram\Bot\Daemon\Daemon->run()
#24 [internal function]: mirocow\telegram\controllers\BotController->actionIndex()
#25 /home/101112.pw/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#26 /home/101112.pw/httpdocs/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#27 /home/101112.pw/httpdocs/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('', Array)
#28 /home/101112.pw/httpdocs/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('', Array)
#29 /home/101112.pw/httpdocs/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('telegram/bot', Array)
#30 /home/101112.pw/httpdocs/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('telegram/bot', Array)
#31 /home/101112.pw/httpdocs/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#32 /home/101112.pw/httpdocs/yii(23): yii\base\Application->run()
#33 {main}

```

**Comment by zelenin** [comment]
it's telegram servers issue.
https://github.com/zelenin/telegram-bot-api/commit/758867107c414eaca6cf4b8e2236136055ddbaff
